streaming_mode: live
resolutions:
  - 720p
  - 480p
  - 360p
audio_codecs:
  - aac
video_codecs:
  - h264
manifest_format:
  - hls
segment_size: 2
availability_window: 200
presentation_delay: 50
update_period: 2